---

  - hosts: linux
    
    
    tasks:
    - name: update apt cache
      ansible.builtin.package:        
        update_cache: true
          
    - name: install apache2 and php_library
      ansible.builtin.package:        
        state: latest
        name:
          - '{{ apache_sunucu }}'
          - '{{ php_library }}'
      

  
    
  
        
        
        