---

  - hosts: ubuntu
    
    
    tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_distribution == "Ubuntu"    
    - name: install apache2
      ansible.builtin.apt:
        state: latest
        name:
          - net-tools
          - curl
      when: ansible_distribution == "Ubuntu"

  - hosts: centos
    tasks:
    - name: update cache in centos
      ansible.builtin.dnf:
        update_cache: yes
    - name: install httpd
      ansible.builtin.dnf:
        state: latest
        name:
          - httpd

    
  
        
        
        