# ---

  # - hosts: linux
  #   #tags: always
  #   tags: never
  #   tasks:
  #   - name: update apt cache
  #     ansible.builtin.package:
  #       update_cache: yes
  #       upgrade: dist
  #     when: ansible_distribution == "Ubuntu"
  #   - name: update & upgrade        
  #     ansible.builtin.package:
  #       update_cache: yes
  #       update_only: yes
  #     when: ansible_distribution == "CentOS"

  
  - hosts: controller
    
    name: pull git weppage to local
    roles: 
      - ansible_controller


#####################################################
#################### build frontend ####################
  - hosts: frontend
    name: build frontend from github
    roles:
      - frontend
# ########################################################     
# ################ build database #######################
  - hosts: database
    tags: database
    name: create database
    roles:
      - database
    
# ########################################################
# ################### build ftp server ################        

  - hosts: ftp_server
    tags: ftp_server
    name: create ftp_server
    roles:
      - ftp_server
    
  
      
  
        