

- name: import vars    
  ansible.builtin.include_vars:
    ../vars/{{ ansible_distribution }}.yaml
    
- name: ftp server install      
  ansible.builtin.package:
    name:
      - '{{ ftpserver }}'
    state: latest
- name: Start the service
  ansible.builtin.systemd:
    name: vsftpd
    state: started